"""add_esco_occupations_and_skills_schema

Revision ID: c6122c06868b
Revises: a2ba8f2d329e
Create Date: 2026-09-05 11:58:07.191824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6122c06868b'
down_revision: Union[str, Sequence[str], None] = 'a2ba8f2d329e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('occupations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('esco_uri', sa.String(length=500), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_occupations_esco_uri'), 'occupations', ['esco_uri'], unique=True)
    op.create_index(op.f('ix_occupations_id'), 'occupations', ['id'], unique=False)
    op.create_index(op.f('ix_occupations_title'), 'occupations', ['title'], unique=False)
    op.create_table('occupation_skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('occupation_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('relation_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['occupation_id'], ['occupations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('occupation_id', 'skill_id', name='uq_occupation_skill')
    )
    op.create_index(op.f('ix_occupation_skills_id'), 'occupation_skills', ['id'], unique=False)
    op.create_index(op.f('ix_occupation_skills_occupation_id'), 'occupation_skills', ['occupation_id'], unique=False)
    op.create_index(op.f('ix_occupation_skills_relation_type'), 'occupation_skills', ['relation_type'], unique=False)
    op.create_index(op.f('ix_occupation_skills_skill_id'), 'occupation_skills', ['skill_id'], unique=False)
    op.add_column('skills', sa.Column('esco_uri', sa.String(length=500), nullable=True))
    op.add_column('skills', sa.Column('title', sa.String(length=255), nullable=True))
    op.add_column('skills', sa.Column('skill_type', sa.String(length=100), nullable=True))
    op.add_column('skills', sa.Column('language', sa.String(length=10), nullable=True))
    op.alter_column('skills', 'name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.create_index(op.f('ix_skills_esco_uri'), 'skills', ['esco_uri'], unique=True)
    op.create_index(op.f('ix_skills_title'), 'skills', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_skills_title'), table_name='skills')
    op.drop_index(op.f('ix_skills_esco_uri'), table_name='skills')
    op.alter_column('skills', 'name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_column('skills', 'language')
    op.drop_column('skills', 'skill_type')
    op.drop_column('skills', 'title')
    op.drop_column('skills', 'esco_uri')
    op.drop_index(op.f('ix_occupation_skills_skill_id'), table_name='occupation_skills')
    op.drop_index(op.f('ix_occupation_skills_relation_type'), table_name='occupation_skills')
    op.drop_index(op.f('ix_occupation_skills_occupation_id'), table_name='occupation_skills')
    op.drop_index(op.f('ix_occupation_skills_id'), table_name='occupation_skills')
    op.drop_table('occupation_skills')
    op.drop_index(op.f('ix_occupations_title'), table_name='occupations')
    op.drop_index(op.f('ix_occupations_id'), table_name='occupations')
    op.drop_index(op.f('ix_occupations_esco_uri'), table_name='occupations')
    op.drop_table('occupations')
    # ### end Alembic commands ###
